### ISSUE TITLE
Have python version ?

### ISSUE THREAD

**Issue by ucasiggcas** [adamstark/BTrack#10]
Dear,

Thanks for your great project.

Do you develop the python version for beat tracking?

And I want to get the BPM at real time, Could U help me ?

Any advice or suggestion will be Okey

**Comment by adamstark** [comment]
Hi there, there is a Python module included in the project:

https://github.com/adamstark/BTrack/tree/master/modules-and-plug-ins/python-module

In the C++ version the `getCurrentTempoEstimate();` function will give you real-time tempo updates. And in the Python module you can get the tempo curve by looking at the time between beats.

**Comment by hyzhan** [comment]
@adamstark,  Thanks for your project.
I try to install python version and got an error. "btrack_python_module.cpp:297:49: error: ‘Py_InitModule’ was not declared in this scope"

**Comment by hyzhan** [comment]
It seem to work on python2, how to tranfer to python3?

**Comment by adamstark** [comment]
I think I would need to re-write it to make it work with Python 3. I don't have time at the moment to do that but I will make a note and try to do that in the future
