### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by AndreeaNicolescu** [adamstark/BTrack#2]
Hello, I have followed the instructions from the Readme, included the header file BTrack.h in a main.cpp file created, and all the headers and cpp's file are in the same folder with main.cpp.However, when I try to instantiate a BTrack object, I get the following error at compile: undefined reference to `BTrack::BTrack(int, int). I tried a few other things but none of them worked. What is the problem ?

**Comment by adamstark** [comment]
Hi,

It sounds like you are not including the BTrack .cpp files - i.e. you need all the BTrack files, not just the headers. It sounds like it can find the header files, but not the implementations. Let me know if that helps!

Thanks,

Adam

**Comment by AndreeaNicolescu** [comment]
I included BTrack.cpp and it worked. Thank you!

**Comment by adamstark** [comment]
No problem! :)
