### ISSUE TITLE
inaccuracy on windows C# wrapper

### ISSUE THREAD

**Issue by polardegausser** [adamstark/BTrack#7]
Greetings,

I'm building some custom camera switching software for BMD video switcher and I decided to implement beat driven switching for long live events with DJ sets. Your code is the only one I found to be simple enough to interface and to give it a try with porting to c# so I don't need to write beat tracking from scratch.
My software is written in C# .net 4.6.1 and uses NAudio library for live audio sampling from soundcard input. I wrote a simple managed C++/CLI DLL to interface unmanaged static lib compiled from Your source. Here's the wrapper class (sorry for unmarked code, github was giving me troubles, I couldn't embed it in one piece so i gave up from styling):

// BTrackWrapper.h
#include <windows.h>  
#include <vcclr.h>  
#using <System.dll> 

#pragma unmanaged 
#include "BTrack.h"
#include "OnsetDetectionFunction.h"
#pragma once

#pragma managed

using namespace System;

namespace BTrackWrapper {
	public ref class BTrackWrapper
	{
	public:
		BTrackWrapper() : m_Impl(new BTrack) {}
		BTrackWrapper(int hopSize) : m_Impl(new BTrack(hopSize)) {}
		BTrackWrapper(int hopSize, int frameSize) : m_Impl(new BTrack(hopSize, frameSize)) {}
		~BTrackWrapper() {
			delete m_Impl;
		}
	protected:
		!BTrackWrapper() {
			delete m_Impl;
		}
	public:
		void processAudioFrameWrapper(System::IntPtr frame) {
				m_Impl->processAudioFrame((double*)((int)frame));
		}

		void processOnsetDetectionFunctionSampleWrapper(double sample) {
			m_Impl->processOnsetDetectionFunctionSample(sample);
		}

		bool beatDueInCurrentFrameWrapper() {
			return bool (m_Impl->beatDueInCurrentFrame());
		}

		void fixTempoWrapper(double tempo) {
			m_Impl->fixTempo(tempo);
		}

		double getCurrentTempoEstimate() {
			return double(m_Impl->getCurrentTempoEstimate());
		}
	private:
		BTrack * m_Impl;
	};
}

In C# code, I create instance with window and hop size and use methods as supposed:

...
BTrackWrapper.BTrackWrapper btw = new BTrackWrapper.BTrackWrapper(512, 1024);
...
//sampling 1024 samples and forwarding them to BTracker with some pin_pointers
      private void OnDataAvailable(object sender, WaveInEventArgs args)
        {
            List<double> frame = new List<double>();
            // interpret as 16 bit audio
            for (int index = 0; index < args.BytesRecorded; index += 2)
            {
                short sample = (short)((args.Buffer[index + 1] << 8) |
                        args.Buffer[index + 0]);
                // to floating point
                var sample32 = sample / 32768.0;
                //sample32 = lpf.Transform(sample32);
                frame.Add(sample32);
            }

            var framearray = frame.ToArray();
            GCHandle handle = GCHandle.Alloc(framearray, GCHandleType.Pinned);
            var framePtr = handle.AddrOfPinnedObject();
            btw.processAudioFrameWrapper(framePtr);
            
            if (btw.beatDueInCurrentFrameWrapper())
            {
                //camera switching
            }
            handle.Free();
        }

I had some problems with compiling libsamplerate but i finally managed to do a successful build. It works, well kind of. It seems very inaccurate and slow for some reason - bpm is usually underestimated, being reported as about 70ish percent of real value. But something that bugs me more is how rarely it actually detects beat. It does the detection about every 10-13 real beats and usually drifts because od tempo mismatch, then corrects itself a bit and drifts again and so on.. 
Do You have any idea what could be a problem or maybe you came across such issue yourself? I tried modifying some basic values in BTracker such as alpha and tightness but it didn't really help much. I also tried taking only one audio channel (sampling twice as long of a period and incrementing index by 4) with same results.

Thank You in advance for reply!

**Comment by polardegausser** [comment]
I'm sorry,

it was just my stupid mistake, my buffer went a lot over 1024 samples. i sampled over 256 milliseconds on 44100Hz...
I'll upload the C# wrapper to github when I analyze it a bit more to make sure there are no leaks or anything like that.

Best regards!

**Comment by adamstark** [comment]
No problem! Hope you enjoy using the library :)

**Comment by mhusinsky** [comment]
@polardegausser 
very interesting stuff, i'm glad i found this issue! i was thinking about doing a wrapper for .net as well but i don't have a lot of experience doing this. it would be really cool if you would share your project to not have to start from scratch :) 
thanks!

**Comment by polardegausser** [comment]
Not a problem, I'll do it later tonight, I need to find it first :)

**Comment by polardegausser** [comment]
Source is a bit of a mess, it was compiled on the fly and banged together just to work. Give me a day or two to tidy up, get rid of absolute paths to dependencies and structure it a bit better and I'll put it here:
[https://github.com/polardegausser/BTrack-Wrapper](url)

**Comment by mhusinsky** [comment]
awesome - a big thank you for that!
